/**
 * AI Service Watchlist
 *
 * Curated list of high-profile AI services that should be in the Trust Index.
 * These are platform-only products (no npm/PyPI package) that the registry
 * scanners can't find. The discover-ai-news cron checks this list against
 * the DB and auto-adds any missing entries.
 *
 * To add a new service: append to the WATCHLIST array below.
 * Fields: name, slug, category, publisher, homepage_url, github_org (optional),
 *         logo_url, description, tags
 */

export interface WatchlistEntry {
  name: string
  slug: string
  category: string
  publisher: string
  homepage_url: string
  github_org?: string
  logo_url: string
  description: string
  tags: string[]
  npm_package?: string
  pypi_package?: string
}

export const WATCHLIST: WatchlistEntry[] = [
  // ── Foundation Models & Platforms ──────────────────────────────
  {
    name: 'Google Gemini',
    slug: 'google-gemini',
    category: 'llm',
    publisher: 'Google',
    homepage_url: 'https://gemini.google.com',
    github_org: 'google',
    logo_url: 'https://github.com/google.png?size=80',
    description: 'Google\'s multimodal AI model powering Vertex AI and consumer products',
    tags: ['llm', 'multimodal', 'foundation-model', 'google'],
    pypi_package: 'google-genai',
  },
  {
    name: 'xAI Grok',
    slug: 'xai-grok',
    category: 'llm',
    publisher: 'xAI',
    homepage_url: 'https://x.ai',
    github_org: 'xai-org',
    logo_url: 'https://github.com/xai-org.png?size=80',
    description: 'xAI\'s conversational AI model integrated with X platform',
    tags: ['llm', 'foundation-model', 'xai'],
  },
  {
    name: 'Perplexity',
    slug: 'perplexity',
    category: 'web-search',
    publisher: 'Perplexity AI',
    homepage_url: 'https://perplexity.ai',
    logo_url: 'https://www.google.com/s2/favicons?domain=perplexity.ai&sz=128',
    description: 'AI-powered answer engine combining search with language models',
    tags: ['search', 'llm', 'ai-search'],
  },
  {
    name: 'DeepSeek',
    slug: 'deepseek',
    category: 'llm',
    publisher: 'DeepSeek',
    homepage_url: 'https://deepseek.com',
    github_org: 'deepseek-ai',
    logo_url: 'https://github.com/deepseek-ai.png?size=80',
    description: 'Open-source large language models with strong reasoning capabilities',
    tags: ['llm', 'open-source', 'foundation-model'],
    pypi_package: 'deepseek',
  },

  // ── AI Coding Tools ────────────────────────────────────────────
  {
    name: 'Cursor',
    slug: 'cursor',
    category: 'code',
    publisher: 'Anysphere',
    homepage_url: 'https://cursor.com',
    github_org: 'getcursor',
    logo_url: 'https://www.google.com/s2/favicons?domain=cursor.com&sz=128',
    description: 'AI-first code editor built on VS Code with integrated AI assistance',
    tags: ['ai-coding', 'ide', 'code-assistant'],
  },
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    category: 'code',
    publisher: 'GitHub',
    homepage_url: 'https://github.com/features/copilot',
    github_org: 'github',
    logo_url: 'https://github.com/github.png?size=80',
    description: 'AI pair programmer that suggests code completions and entire functions',
    tags: ['ai-coding', 'code-assistant', 'copilot'],
  },
  {
    name: 'Claude Code',
    slug: 'claude-code',
    category: 'code',
    publisher: 'Anthropic',
    homepage_url: 'https://docs.anthropic.com/en/docs/agents-and-tools/claude-code/overview',
    github_org: 'anthropics',
    logo_url: 'https://github.com/anthropics.png?size=80',
    description: 'Anthropic\'s agentic coding tool for terminal-based development',
    tags: ['ai-coding', 'agent', 'cli', 'anthropic'],
  },
  {
    name: 'Windsurf',
    slug: 'windsurf',
    category: 'code',
    publisher: 'Codeium',
    homepage_url: 'https://windsurf.com',
    github_org: 'codeium',
    logo_url: 'https://www.google.com/s2/favicons?domain=windsurf.com&sz=128',
    description: 'AI-powered IDE with agentic coding capabilities',
    tags: ['ai-coding', 'ide', 'code-assistant'],
  },
  {
    name: 'Devin',
    slug: 'devin',
    category: 'code',
    publisher: 'Cognition AI',
    homepage_url: 'https://devin.ai',
    github_org: 'cognition-ai',
    logo_url: 'https://www.google.com/s2/favicons?domain=devin.ai&sz=128',
    description: 'Autonomous AI software engineer for end-to-end development tasks',
    tags: ['ai-coding', 'agent', 'autonomous'],
  },
  {
    name: 'Codex CLI',
    slug: 'codex-cli',
    category: 'code',
    publisher: 'OpenAI',
    homepage_url: 'https://github.com/openai/codex',
    github_org: 'openai',
    logo_url: 'https://github.com/openai.png?size=80',
    description: 'OpenAI\'s terminal-based coding agent',
    tags: ['ai-coding', 'agent', 'cli', 'openai'],
  },
  {
    name: 'Tabnine',
    slug: 'tabnine',
    category: 'code',
    publisher: 'Tabnine',
    homepage_url: 'https://tabnine.com',
    github_org: 'codota',
    logo_url: 'https://github.com/codota.png?size=80',
    description: 'AI code completion tool for enterprise development teams',
    tags: ['ai-coding', 'code-assistant', 'enterprise'],
  },
  {
    name: 'Replit',
    slug: 'replit',
    category: 'code',
    publisher: 'Replit',
    homepage_url: 'https://replit.com',
    github_org: 'replit',
    logo_url: 'https://github.com/replit.png?size=80',
    description: 'Browser-based IDE with AI-powered development and deployment',
    tags: ['ai-coding', 'ide', 'cloud', 'agent'],
  },

  // ── AI App Builders ────────────────────────────────────────────
  {
    name: 'Bolt.new',
    slug: 'bolt-new',
    category: 'code',
    publisher: 'StackBlitz',
    homepage_url: 'https://bolt.new',
    github_org: 'stackblitz',
    logo_url: 'https://www.google.com/s2/favicons?domain=bolt.new&sz=128',
    description: 'AI-powered full-stack web app builder in the browser',
    tags: ['ai-coding', 'app-builder', 'web'],
  },
  {
    name: 'Lovable',
    slug: 'lovable',
    category: 'code',
    publisher: 'Lovable',
    homepage_url: 'https://lovable.dev',
    github_org: 'lovable-dev',
    logo_url: 'https://www.google.com/s2/favicons?domain=lovable.dev&sz=128',
    description: 'AI-powered app generation from natural language prompts',
    tags: ['ai-coding', 'app-builder', 'web'],
  },
  {
    name: 'v0 by Vercel',
    slug: 'v0-vercel',
    category: 'code',
    publisher: 'Vercel',
    homepage_url: 'https://v0.dev',
    github_org: 'vercel',
    logo_url: 'https://www.google.com/s2/favicons?domain=v0.dev&sz=128',
    description: 'AI UI generation tool from Vercel for React components',
    tags: ['ai-coding', 'ui-generation', 'react'],
  },

  // ── Workflow Automation ────────────────────────────────────────
  {
    name: 'Zapier AI',
    slug: 'zapier',
    category: 'agent',
    publisher: 'Zapier',
    homepage_url: 'https://zapier.com',
    github_org: 'zapier',
    logo_url: 'https://github.com/zapier.png?size=80',
    description: 'AI-enhanced workflow automation connecting 7,000+ apps',
    tags: ['workflow', 'automation', 'integration'],
  },
  {
    name: 'Make',
    slug: 'make',
    category: 'agent',
    publisher: 'Make',
    homepage_url: 'https://make.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=make.com&sz=128',
    description: 'Visual workflow automation platform with AI capabilities',
    tags: ['workflow', 'automation', 'visual'],
  },

  // ── Inference Providers ────────────────────────────────────────
  {
    name: 'Cerebras',
    slug: 'cerebras',
    category: 'infra',
    publisher: 'Cerebras',
    homepage_url: 'https://cerebras.ai',
    github_org: 'cerebras',
    logo_url: 'https://github.com/cerebras.png?size=80',
    description: 'Wafer-scale inference engine delivering the fastest AI compute',
    tags: ['inference', 'hardware', 'compute'],
    pypi_package: 'cerebras-cloud-sdk',
  },
  {
    name: 'SambaNova',
    slug: 'sambanova',
    category: 'infra',
    publisher: 'SambaNova',
    homepage_url: 'https://sambanova.ai',
    github_org: 'sambanova',
    logo_url: 'https://github.com/sambanova.png?size=80',
    description: 'Custom silicon platform for enterprise AI inference',
    tags: ['inference', 'hardware', 'enterprise'],
  },

  // ── Cloud AI Platforms ─────────────────────────────────────────
  {
    name: 'Amazon Bedrock',
    slug: 'amazon-bedrock',
    category: 'infra',
    publisher: 'Amazon Web Services',
    homepage_url: 'https://aws.amazon.com/bedrock',
    github_org: 'aws',
    logo_url: 'https://github.com/aws.png?size=80',
    description: 'AWS fully managed service for foundation model access and orchestration',
    tags: ['cloud', 'foundation-model', 'aws'],
    npm_package: '@aws-sdk/client-bedrock',
  },
  {
    name: 'Amazon Q Developer',
    slug: 'amazon-q',
    category: 'code',
    publisher: 'Amazon Web Services',
    homepage_url: 'https://aws.amazon.com/q/developer',
    github_org: 'aws',
    logo_url: 'https://github.com/aws.png?size=80',
    description: 'AWS AI-powered coding assistant for development workflows',
    tags: ['ai-coding', 'cloud', 'aws'],
  },
  {
    name: 'Gemini Code Assist',
    slug: 'gemini-code-assist',
    category: 'code',
    publisher: 'Google',
    homepage_url: 'https://cloud.google.com/gemini/docs/codeassist/overview',
    github_org: 'google',
    logo_url: 'https://github.com/google.png?size=80',
    description: 'Google Cloud AI-powered code completion and assistance',
    tags: ['ai-coding', 'cloud', 'google'],
  },
  {
    name: 'Microsoft Copilot',
    slug: 'microsoft-copilot',
    category: 'agent',
    publisher: 'Microsoft',
    homepage_url: 'https://copilot.microsoft.com',
    github_org: 'microsoft',
    logo_url: 'https://github.com/microsoft.png?size=80',
    description: 'AI assistant integrated across Microsoft 365 and Windows',
    tags: ['ai-assistant', 'productivity', 'microsoft'],
  },

  // ── Infrastructure (Our Sources) ───────────────────────────────
  {
    name: 'OpenClaw',
    slug: 'openclaw',
    category: 'infra',
    publisher: 'OpenClaw',
    homepage_url: 'https://clawhub.org',
    github_org: 'openclaw',
    logo_url: 'https://github.com/openclaw.png?size=80',
    description: 'Open registry for AI agent skills and capabilities',
    tags: ['registry', 'agent', 'mcp', 'skills'],
  },
  {
    name: 'OSV.dev',
    slug: 'osv-dev',
    category: 'infra',
    publisher: 'Google',
    homepage_url: 'https://osv.dev',
    github_org: 'google',
    logo_url: 'https://github.com/google.png?size=80',
    description: 'Open source vulnerability database for the open source ecosystem',
    tags: ['security', 'vulnerability', 'database'],
  },
  {
    name: 'VirusTotal',
    slug: 'virustotal',
    category: 'infra',
    publisher: 'Google',
    homepage_url: 'https://virustotal.com',
    github_org: 'virustotal',
    logo_url: 'https://github.com/virustotal.png?size=80',
    description: 'Malware and URL scanning service for security analysis',
    tags: ['security', 'malware', 'scanning'],
  },

  // ── Creative AI ────────────────────────────────────────────────
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    category: 'speech',
    publisher: 'ElevenLabs',
    homepage_url: 'https://elevenlabs.io',
    github_org: 'elevenlabs',
    logo_url: 'https://github.com/elevenlabs.png?size=80',
    description: 'AI voice generation platform with emotion, music, and dubbing',
    tags: ['voice', 'text-to-speech', 'audio'],
    pypi_package: 'elevenlabs',
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    category: 'image-generation',
    publisher: 'Midjourney',
    homepage_url: 'https://midjourney.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=midjourney.com&sz=128',
    description: 'AI image generation with unmatched artistic quality',
    tags: ['image-generation', 'creative', 'art'],
  },
  {
    name: 'Runway',
    slug: 'runway',
    category: 'image-generation',
    publisher: 'Runway',
    homepage_url: 'https://runwayml.com',
    github_org: 'runwayml',
    logo_url: 'https://github.com/runwayml.png?size=80',
    description: 'AI video generation and editing platform',
    tags: ['video-generation', 'creative', 'editing'],
  },
  {
    name: 'Synthesia',
    slug: 'synthesia',
    category: 'speech',
    publisher: 'Synthesia',
    homepage_url: 'https://synthesia.io',
    logo_url: 'https://www.google.com/s2/favicons?domain=synthesia.io&sz=128',
    description: 'AI video avatar platform for business communications',
    tags: ['video', 'avatar', 'enterprise'],
  },
  {
    name: 'DALL-E',
    slug: 'dall-e',
    category: 'image-generation',
    publisher: 'OpenAI',
    homepage_url: 'https://openai.com/dall-e',
    github_org: 'openai',
    logo_url: 'https://github.com/openai.png?size=80',
    description: 'OpenAI\'s text-to-image generation model',
    tags: ['image-generation', 'openai'],
  },
  {
    name: 'Sora',
    slug: 'sora',
    category: 'image-generation',
    publisher: 'OpenAI',
    homepage_url: 'https://openai.com/sora',
    github_org: 'openai',
    logo_url: 'https://github.com/openai.png?size=80',
    description: 'OpenAI\'s text-to-video generation model',
    tags: ['video-generation', 'openai'],
  },

  // ── Design & Creative AI ───────────────────────────────────────
  {
    name: 'QuiverAI',
    slug: 'quiverai',
    category: 'image-generation',
    publisher: 'QuiverAI',
    homepage_url: 'https://quiver.ai',
    github_org: 'quiverai',
    logo_url: 'https://github.com/quiverai.png?size=80',
    description: 'Frontier AI models for generating, editing, and animating vector graphics (SVG)',
    tags: ['image-generation', 'svg', 'vector', 'design', 'api'],
  },

  // ── Security ───────────────────────────────────────────────────
  {
    name: 'Dify',
    slug: 'dify',
    category: 'framework',
    publisher: 'LangGenius',
    homepage_url: 'https://dify.ai',
    github_org: 'langgenius',
    logo_url: 'https://github.com/langgenius.png?size=80',
    description: 'Open-source LLM application development platform',
    tags: ['framework', 'llm', 'app-builder'],
  },
  {
    name: 'NotebookLM',
    slug: 'notebooklm',
    category: 'llm',
    publisher: 'Google',
    homepage_url: 'https://notebooklm.google.com',
    github_org: 'google',
    logo_url: 'https://github.com/google.png?size=80',
    description: 'Google AI research assistant that works with your documents',
    tags: ['research', 'documents', 'google'],
  },
]
